server:
  port: 8080

spring:
  datasource:
    username: root
    password: lll521
    url: jdbc:mysql://192.168.1.11:3306/wangcai?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
   # url: jdbc:mysql://localhost:3306/wangcai?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml


#showSql
logging:
  level:
    com:
      ncell:
        wangcai:
          ConnectionDao : debug